package com.example.miniproyecto_batalla_naval.controller.adapter;

import javafx.event.EventHandler;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;

/**
 * Adapter responsible for handling mouse events on a board cell.
 * This class captures JavaFX mouse events and delegates the corresponding
 * action to a {@link CellInteractionListener}, identifying the selected
 * board position and the mouse button used.
 *
 * @author Juan José Morera Gómez
 * @author Frank Leonardo Silva Castillo
 * @version 1.0
 * @since 1.0
 */
public class CellInteractionAdapter implements EventHandler<MouseEvent> {
    private final int row;
    private final int column;
    private final CellInteractionListener listener;

    /**
     * Creates a new adapter for a specific board cell.
     *
     * @param row the row index of the selected cell
     * @param column the column index of the selected cell
     * @param listener the listener that receives the interaction events
     */
    public CellInteractionAdapter(int row, int column, CellInteractionListener listener) {
        this.row = row;
        this.column = column;
        this.listener = listener;
    }

    /**
     * Handles mouse events generated on the associated board cell.
     * A primary mouse click is interpreted as a left click, while
     * a secondary mouse click is interpreted as a right click.
     *
     * @param event the mouse event generated by JavaFX
     */
    @Override
    public void handle(MouseEvent event) {
        if (event.getButton() == MouseButton.PRIMARY) {
            listener.onCellLeftClick(row, column);
        } else if (event.getButton() == MouseButton.SECONDARY) {
            listener.onCellRightClick(row, column);
        }
    }
}