package com.example.miniproyecto_batalla_naval.controller.adapter;

import javafx.event.EventHandler;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;

/**
 * Adapter responsible for handling keyboard events related to ship rotation.
 * This class listens for JavaFX key events and delegates rotation requests
 * to a {@link RotationListener} when the corresponding key is pressed.
 * Currently, the rotation action is triggered by the Space key.
 *
 * @author Juan José Morera Gómez
 * @author Frank Leonardo Silva Castillo
 * @version 1.0
 * @since 1.0
 */
public class KeyRotationAdapter implements EventHandler<KeyEvent> {

    private final RotationListener listener;

    /**
     * Creates a new keyboard rotation adapter.
     *
     * @param listener the listener that handles ship rotation requests
     */
    public KeyRotationAdapter(RotationListener listener) {
        this.listener = listener;
    }

    /**
     * Handles keyboard events generated by JavaFX.
     * If the Space key is pressed, a rotation request is sent to the
     * associated {@link RotationListener} and the event is consumed
     * to prevent further propagation.
     *
     * @param event the keyboard event generated by JavaFX
     */
    @Override
    public void handle(KeyEvent event) {
        if (event.getCode() == KeyCode.SPACE) {
            listener.onRotateRequested();
            event.consume();
        }
    }
}